### ISSUE TITLE
Sometime one or more files were wipe out all contents

### ISSUE THREAD

**Issue by basheewang** [MagicDuck/grug-far.nvim#160] opened 2024-07-26 05:15 UTC
It happened a few times to me. Fortunately I have version control to revert back. I still has no idea what will trigger this bug, so I can't reproduce it.  I am using nightly build neovim with NvChad config, and update the grug-far to latest version.

**Suggestions**: Please add undo function if a replace happens and not meet my requirements or triggered the above bug, it can revert all changes back.

![image](https://github.com/user-attachments/assets/c39c06d9-4c81-49b1-9d7f-277861860f3d)

**Comment by MagicDuck** [comment] 2024-07-26 15:39
Unfortunately, undo is not possible, or would likely be extremely difficult. What action were you executing when this happened? Replace? There’s been some changes to replace just yesterday so hopefully that helps a bit. I have never seen this myself, but will keep an eye out. If you get more of a clue on the reproduction steps, please add to this ticket

**Comment by MagicDuck** [comment] 2024-07-26 15:41
Also check :messages when this happens to see if there are any errors reported

**Comment by MagicDuck** [comment] 2024-07-26 23:59
@basheewang I've done some refactors on `replace` to make it more bulletproof. In theory now it will never do a replace with empty content on a file.
 
I'll close this bug for now, for issue management purposes and because there is no real additional action that can be taken.
Feel free to re-open if you see the problem again though! 😄

**Closed by MagicDuck** 2024-07-26 23:59 UTC
Labels: under-observation
