### ISSUE TITLE
Closing grug-far with Ctrl W - O changes the file syntax of the current buffer

### ISSUE THREAD

**Issue by mariano-dagostino** [MagicDuck/grug-far.nvim#298] opened 2024-10-30 13:39 UTC
When I find what I need with grub-far I usually keep the current buffer opened and close the rest using `Ctrl-W + O` this action seems to confuse nvim and the current buffer gets a different syntax language. Hopefully this video will illustrate the problem.

https://github.com/user-attachments/assets/dd81933e-0b35-42c4-a9f4-8cc5c9d7e3d1

**Comment by MagicDuck** [comment] 2024-10-30 23:46
hmm, that's strange, I can't reproduce this myself (tried with both tsc and php files and with minimal repro env). There's probably some other plugin or autocommand that's causing it.

Can you try it with a minimal reproduction config. ex:
`repro.lua`:
```lua
local root = vim.fn.fnamemodify('~/.nvim_repro', ':p')
-- set stdpaths to use .repro
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end
-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    '--single-branch',
    'https://github.com/folke/lazy.nvim.git',
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.g.maplocalleader = ','
-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  'folke/tokyonight.nvim',
  {
    "MagicDuck/grug-far.nvim",
    config = function()
      require('grug-far').setup({})
    end,
  },
  -- add any other pugins here
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})

-- add anything else here
-- vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```
Then run with:
```sh
nvim -u repro.lua /path/to/somefile.php
```

**Comment by MagicDuck** [comment] 2024-11-05 00:02
@mariano-dagostino any update from your side? Otherwise I'll close the issue...

**Comment by MagicDuck** [comment] 2024-12-03 03:23
@mariano-dagostino closing for issue management purposes since there's been no activity for a month, but we can reopen anytime if you have more data 😄 .

**Closed by MagicDuck** 2024-12-03 03:23 UTC
