### ISSUE TITLE
Inconsistent number of matches & difference with `rg`

### ISSUE THREAD

**Issue by PJGaetan** [MagicDuck/grug-far.nvim#40] opened 2024-05-18 11:36 UTC
I started playing around with `grug-far` today. 
The way it's doing search & replace clicked directly, it's really nice and slick !

I just found one thing that I try to show in the following video.
I have an empty config and I am on commit `43c1970`.

I have seen two problems but they might be related or it might be a misconfiguration on my machine ?
- Inconsistency of search results
- I don't have all of the results that I would normally get from `rg` (I can see the flag `--regexp` is used to run the search in the code, but the results are the same with and without)

https://github.com/MagicDuck/grug-far.nvim/assets/43468407/726d0192-e313-4fab-bc0f-830273e3834e

**Comment by MagicDuck** [comment] 2024-05-18 17:33
Hmm, good find! I will take a look soon!

**Comment by MagicDuck** [comment] 2024-05-18 19:43
fixed in https://github.com/MagicDuck/grug-far.nvim/pull/41
looks like just something I screwed up yesterday, so hopefully did not affect too many people.
Your reproduction video was excellent and very helpful in resolving the problem!

**Comment by MagicDuck** [comment] 2024-05-18 19:56
closing, let me know if you still see issues and I'll reopen

**Closed** 2024-05-18 19:56 UTC

**Comment by PJGaetan** [comment] 2024-05-19 17:18
Fully fixed on my end !

**Comment by MagicDuck** [comment] 2024-05-21 20:16
nice, thanks for confirming!
