### ISSUE TITLE
error while try to search and replace 

### ISSUE THREAD

**Issue by albu-ali** [MagicDuck/grug-far.nvim#275] opened 2024-09-26 13:29 UTC
hey I got error when I try to use grug-far 

I also run checkhealth grug-far
and it show me that there is nothing is wrong and not error 

but I still got this error every time I start typing in search and then go the replace!

```Error executing vim.schedule lua callback: .../nvim/lazy/grug-far.nvim/lua/grug-far/actions/search.lua:110: attempt to index field 'stats' (a nil value)
stack traceback:
	.../nvim/lazy/grug-far.nvim/lua/grug-far/actions/search.lua:110: in function 'on_fetch_chunk'
	...azy/grug-far.nvim/lua/grug-far/engine/ripgrep/search.lua:210: in function 'on_finish'
	...azy/grug-far.nvim/lua/grug-far/engine/ripgrep/search.lua:98: in function 'on_finish'
	...grug-far.nvim/lua/grug-far/engine/fetchCommandOutput.lua:56: in function <...grug-far.nvim/lua/grug-far/engine/fetchCommandOutput.lua:54>```

**Comment by albu-ali** [comment] 2024-09-26 16:32
I think the error is from lazyvim more then it's from grug-far!

**Comment by albu-ali** [comment] 2024-09-26 17:54
Hello and sorry, but I am experiencing an issue with the `grug-far` plugin. I reported this problem to the LazyVim team, and they informed me that this issue is related to `grug-far`, not LazyVim itself.

You can find their response here: [LazyVim Issue #4498](https://github.com/LazyVim/LazyVim/issues/4498).

### Steps to Reproduce:
1. Open Neovim.
2. Use the command `<Leader>sr` to initiate `grug-far`.
3. Start typing in to replace and see the error

### Additional Information:
- **Neovim Version:** NVIM v0.10.1
- **Operating System:** Fedora Linux

**Comment by MagicDuck** [comment] 2024-09-27 20:34
hmm, I can't really reproduce that exact error, but I can reproduce an issue which seems related in that some interrupted searches don't finish correctly. I'll investigate!

**Comment by MagicDuck** [comment] 2024-09-28 04:29
@albu-ali I've made some fixes in the logic and I can't reproduce even the thing I was seeing before. Can you update to the latest and see if you are still seeing the problem?

**Comment by albu-ali** [comment] 2024-09-29 16:26
## first I update 


![update](https://github.com/user-attachments/assets/cc1e827e-23c2-42fe-ab97-0fca62794504)


## TIME FOR TESTING, it's look like you done nice fixes but wait!


![before-the-issue](https://github.com/user-attachments/assets/60328534-eede-47b5-80bc-95804e45777e)


## let's do some replace (here is the issue again)


![after-issue-happen](https://github.com/user-attachments/assets/f84d4493-56da-4c80-b388-23e41682157b)


## wait I think here is some little different issue then the one before


![other-issue-with-permission](https://github.com/user-attachments/assets/6f61bd85-62bb-493a-aa81-d018689e58a5)

---

## let's do the same thing with different distro (because some times the problem from the distro and it's packages) Linux Mint

![install-lazyvim](https://github.com/user-attachments/assets/04a7a8e6-bd32-4f5f-8308-35f16b822e42)

## I think it's the same issue, maybe it's little different because the Mint has some old packages (not like fedora and arch)

![test-with-linux-mint](https://github.com/user-attachments/assets/c23158b2-3ba8-4cb4-8048-010bc2cba27c)


## here is the error message that come from Linux mint 

```
E5108: Error executing lua: ...nt/.local/share/nvim/lazy/grug-far.nvim/lua/grug-far.lua:32: Please call require("grug-far").setup(...) beforehand!
stack traceback:
	[C]: in function 'error'
	...nt/.local/share/nvim/lazy/grug-far.nvim/lua/grug-far.lua:32: in function 'ensure_configured'
	...nt/.local/share/nvim/lazy/grug-far.nvim/lua/grug-far.lua:257: in function 'open'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:140: in function <...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:137>
```

**Comment by MagicDuck** [comment] 2024-09-29 16:39
The linux mint one is cause you did not call require(‘grug-far’).setup() in your config like the message says.

For the first one ,it looks like you are not getting the same error message anymore, which is good, just the match not being found when entering replace string. The permission denied one means you have some files which you don’t have permission to that are being searched. That might be the root issue. I likely have an error propagation bug so I will investigate…

**Comment by MagicDuck** [comment] 2024-09-30 01:50
Alrigthty, I think it should be fixed now. It will show all the matches it can find but report errors such as permission errors as warnings. ex:
![image](https://github.com/user-attachments/assets/9eff4807-3fdb-4c0d-9567-017bb4a8669a)

**Comment by albu-ali** [comment] 2024-09-30 10:51
## let's see

![now-that's-working](https://github.com/user-attachments/assets/3366bb02-2408-445c-8051-8c2450d08fb4)

# bro I like the hard work you did!

<p align="center">
    <img src="https://github.com/user-attachments/assets/ee70d620-1668-4c2b-84d6-220bbd7f0a5d" alt="Description" width="400">
</p>

**Closed** 2024-09-30 15:43 UTC
Labels: bug
